### ISSUE TITLE
Move read_in_mutations etc to this repo?

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/sc2ts-paper#237]
I don't think we're using the lineage defining mutations otherwise in sc2ts, so may as well move the whole lot over here?

**Comment by hyanwong** [comment]
We currently are in `sc2ts.utils.plot_subgraph`, so that we can restrict plotting to just the lineage-defining mutations.

We could either move the plot_subgraph function to this repo (but perhaps it's useful in general for anyone looking at sc2ts trees) or pass in the lineage mutation dictionary rather than the filename to the plot_subgraph function. My preference is the latter.

**Comment by jeromekelleher** [comment]
Let's do that for now so

**Comment by hyanwong** [comment]
I just had a look, and the `check_lineages` and `add_gisaid_lineages_to_ts` functions in `utils.py` require a `linmuts_dict` object, so they are still depending on the `lineages.MutationContainer` object, or something that acts like it.

Perhaps we aren't going to use those functions any more though, and they can be stripped out?

**Comment by jeromekelleher** [comment]
I can't we can remove them.

**Comment by hyanwong** [comment]
Done in https://github.com/jeromekelleher/sc2ts/pull/399
